FROM python:3.12-slim

# Set work directory
WORKDIR /app

# Copy your code
COPY subscriber.py . 
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the subscriber
CMD ["python", "subscriber.py"]

